config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root 'pages#home'
  get "/", to: "pages#home"

  resources :products
  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_color_size_and_image

end

app/models/product_color_size_and_image.rb
class ProductColorSizeAndImage < ApplicationRecord
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @products = Product.all
  end
  
end

app/controllers/product_color_size_and_images_controller.rb
class ProductColorSizeAndImagesController < ApplicationController

  def home
    @products_color_size_and_images = ProductColorSizeAndImage.all
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def method_name

  end

  def create
    # if selected_all_answers
      Product.create(
        name: params["product"]["name"],
        category: params["product"]["category"],
        price: params["product"]["price"],
        image: params["product"]['image'],
        size: params["product"]['size'],
        color: params["product"]['color'],
        description: params["product"]['description'],
      )

      redirect_to product_path(id: Product.all.last.id ), notice: "Respostas salvas com sucesso"
      # end

    # else
      # redirect_to questions_path, notice: "Por favor, selecione uma alternativa para cada questão."
    # end
  end

  def index
    @products = Product.all
    @colors_available = @products.map {|product| product.color}.uniq
    @sizes_available = @products.map {|product| product.size}.uniq
    @categories_available = @products.map {|product| product.category}.uniq
    @prices_available = @products.map {|product| product.price}.uniq
  end

  def show
    @product = Product.find(params[:id])
  end

  # def products_params
  #   params.require(:products).permit(:name, :price, :image, :size, :color, :description, :category)
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/product_color_size_and_images_helper.rb
module ProductColorSizeAndImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YouModas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Retirar %>
    <%# /Retirar %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= favicon_link_tag asset_path('favicon.ico') %>

  </head>

  <body>
  <%= render 'shared/header' %>
  <%= render 'shared/navLink' %>
  <%# <%= render 'shared/productSlides' %>
  <%# <%= render 'shared/filterCanvas' %>
  <%# <%= render 'shared/sectionTitle' %>
  <%# <%= render 'shared/homeBagGrid' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/productAddToinventory' %>

<%= render 'shared/homeCarousel' %>

<%= render 'shared/sectionTitle' %>

<%= render 'shared/homeBagGrid' %>


<section class="home-second-body">

  <%= render 'shared/cardsCarouselTitle' %>

  <%= render 'shared/homeCardsCarousel' %>

  <%= render 'shared/trendingTitle' %>

  <%= render 'shared/trendingGrid' %>

  <%= render 'shared/footerMedias' %>

  <%= render 'shared/footerBanner' %>

  <%= render 'shared/footerBody' %>

</section>

app/views/products/index.html.erb
<%= render 'shared/filterCanvas' %>

<%# PRODUCT CARD %>

<%= render 'shared/productsAvailability' %>



<ul>
  <div class="card">
    <% @products[0..1].each do |product| %>
      <img src="https://cdn.shopify.com/s/files/1/0615/7913/products/PNG01137-web_400x400_crop_center.jpg?v=1661316048" alt="Denim Jeans" style="width:100%">
      <h1><%= product.name %></h1>
        <p class="price">R$<%= product.price %></p>
        <p><%= product.description %></p>
        <%= link_to "View more", "/products/#{product.id}" %>
        <p><button link_to>Add to Cart</button></p>
    <% end %>
  </div>
</ul>


  <%# ADD .EACH FOR PRODUCT %>
  <%# <% @products.each do |product| %>
    <%# <li><%= product.address</li> %>
    <%# <td><% if policy(product).show? %>
              <%# <%= link_to "Show", product_path(product) %>
        <%# <% end</td>  %>
    <%# <td><% if policy(product).update? %>
              <%# <%= link_to "Edit", edit_product_path(product) %>
        <%# <% end</td> %>
    <%# <td><% if policy(product).update? %>
              <%# <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%# <% end</td> %>
  <%# <% end %>

app/views/products/show.html.erb
<%= render 'shared/productSlides' %>

app/views/shared/_cardsCarouselTitle.html.erb
<div class="home-second-body-title">
  <div class="divider-container mt-5">
    <span class="nav-divider" style="height: 0.5px; background-color: white"></span>
  </div>
  <h1 class="home-latest-title js-animation">NOVIDADES</h1>
  <div class="divider-container">
      <span class="nav-divider" style="height: 2px; background-color: white"></span>
  </div>
  <p class="home-latest-paragraph">Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam recusandae asperiores.</p>
</div>

app/views/shared/_filtercanvas.html.erb
<button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">Filtrar</button>

<div class="offcanvas offcanvas-start canvas-container" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasScrollingLabel"></h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
  <h5>Categorias</h5>
    <ul>
      <li><a href="/">BLUSAS</a></li>
      <li><a href="/">CALÇAS</a></li>
      <li><a href="/">SAIAS</a></li>
      <li><a href="/">SHORTS</a></li>
      <li><a href="/">VESTIDOS</a></li>
      <li><a href="/">ACESSÓRIOS</a></li>
    </ul>
    <h5>Tamanhos</h5>
      <div class="form-check form-check-inline canvas-size-checks">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
        <label class="form-check-label" for="inlineCheckbox1">PP</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
        <label class="form-check-label" for="inlineCheckbox1">P</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="option2">
        <label class="form-check-label" for="inlineCheckbox2">M</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3">
        <label class="form-check-label" for="inlineCheckbox3">G</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3">
        <label class="form-check-label" for="inlineCheckbox3">GG</label>
      </div>

      <br>

      <div class="form-check form-check-inline canvas-size-checks">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
        <label class="form-check-label" for="inlineCheckbox1">34</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
        <label class="form-check-label" for="inlineCheckbox1">36</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="option2">
        <label class="form-check-label" for="inlineCheckbox2">38</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3">
        <label class="form-check-label" for="inlineCheckbox3">40</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3">
        <label class="form-check-label" for="inlineCheckbox3">42</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3">
        <label class="form-check-label" for="inlineCheckbox3">44</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3">
        <label class="form-check-label" for="inlineCheckbox3">46</label>
      </div>


  </div>
</div>

app/views/shared/_footerBanner.html.erb
<div class="container-fluid p-0">
  <div class="footer-img-banner">
    <%# <div class="footer-text-div"> %>
      <div class="d-flex justify-content-center align-items-center h-100">
        <div class="text-white">
          <h1 class="mb-3">Heading</h1>
          <h4 class="mb-3">Subheading</h4>
          <a class="btn btn-outline-light btn-lg" href="#!" role="button"
          >Call to action</a
          >
        </div>
      </div>
    <%# </div> %>
  </div>
</div>

app/views/shared/_footerBody.html.erb
<div class="container-fluid pb-0 mb-0 justify-content-center text-light footer-body-main-container">
  <footer>
    <div class="row justify-content-center footer-body-container">
      <div class="col-11">
        <div class="row ">
          <div class="col-xl-8 col-md-4 col-sm-4 col-12 my-auto mx-auto a">
            <%= link_to '/', class: "header-logo" do %>
              <%= image_tag "logo-footer.png" %>
            <% end %>
            <%# <h3 class="text-muted mb-md-0 mb-5 bold-text footer-logo">Pepper.</h3> %>
          </div>

          <div class="col-xl-2 col-md-4 col-sm-4 col-12">
            <h6 class="mb-3 mb-lg-4 bold-text"><b>MENU</b>
            </h6>
            <ul class="list-unstyled">
              <li>Home</li>
              <li>About</li>
              <li>Blog</li>
              <li>Portfolio</li>
            </ul>
          </div>

          <div class="col-xl-2 col-md-4 col-sm-4 col-12">
            <h6 class="mb-3 mb-lg-4 text-muted bold-text mt-sm-0 mt-5">
              <b>ADDRESS</b>
            </h6>
            <p class="mb-1">605, RUA TIRADENTES</p>
            <p>CENTRO</p>
          </div>
        </div>

        <div class="row ">
          <div class="col-xl-8 col-md-4 col-sm-4 col-auto my-md-0 mt-5 order-sm-1 order-3 align-self-end">
            <p class="social text-muted mb-0 pb-0 bold-text">
              <span  class="mx-2">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </span>
              <span class="mx-2">
                <i class="fa fa-linkedin-square" aria-hidden="true"></i>
              </span>
              <span class="mx-2">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </span>
              <span class="mx-2">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </span>
            </p>

            <small class="rights"><span>&#174;</span>
              YouModas All Rights Reserved.
            </small>
          </div>

          <div class="col-xl-2 col-md-4 col-sm-4 col-auto order-1 align-self-end">
            <h6 class="mt-55 mt-2 text-muted bold-text">
              <b>FULANA</b>
            </h6>
            <small>
              <span>
                <i class="fa fa-envelope" aria-hidden="true"></i>
              </span> fulana@gmail.com
            </small>
          </div>

          <div class="col-xl-2 col-md-4 col-sm-4 col-auto order-2 align-self-end mt-3">
            <h6 class="text-muted bold-text">
              <b>SICLANA</b>
            </h6>
            <small>
              <span>
                <i class="fa fa-envelope" aria-hidden="true"></i>
              </span> siclana@gmail.com
            </small>
          </div>
        </div>
      </div>
    </div>
  </footer>
</div>

app/views/shared/_footerMedias.html.erb
<section class="d-flex justify-content-between p-4 mt-5 footer-medias-main-container" style="background-color: white">

  <div class="me-5">
    <span style="color: #C58E84" >Get connected with us on social networks:</span>
  </div>

  <div>
    <a href="/" class="me-4" style="color: #C58E84; text-decoration: none">
      <i class="bi bi-facebook"></i>
    </a>
    <a href="/" class="me-4" style="color: #C58E84; text-decoration: none">
      <i class="bi bi-twitter"></i>
    </a>
    <a href="/" class="me-4" style="color: #C58E84; text-decoration: none">
      <i class="bi bi-google"></i>
    </a>
    <a href="/" class="me-4" style="color: #C58E84; text-decoration: none">
      <i class="bi bi-instagram"></i>
    </a>
    <a href="/" class="me-4" style="color: #C58E84; text-decoration: none">
      <i class="fab fa-linkedin"></i>
    </a>
    <a href="/" class="me-4" style="color: #C58E84; text-decoration: none">
      <i class="fab fa-github"></i>
    </a>
  </div>

</section>

app/views/shared/_header.html.erb
<%# HEADER  %>

<header class="header-container pt-4">
  <%= link_to '/', class: "header-logo" do %>
    <%= image_tag "LOGOTIPO2.png" %>
  <% end %>

  <form class="search-bar-container" onsubmit="event.preventDefault();" role="search">
    <label class="search-bar-label" for="search">Search for stuff</label>
    <input class="search-bar-input" id="search" type="search" placeholder="Procurar..." autofocus required />
    <button class="search-bar-btn" type="submit"><i class="fas fa-search search-lupa-icon"></i></button>
  </form>

  <div class="header-cart-container">
    <%= link_to "/", class: "cartbag-link" do %>
      <%= image_tag "cartbag-icon.png", class: "cartbag-img" %>
      <% end %>
  </div>
</header>



<%# DIVIDER %>

<div class="divider-container mb-4">
  <span class="nav-divider"></span>
</div>

app/views/shared/_homeCardsCarousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide home-cards-carousel" data-bs-ride="true">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>

  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="cards-carousel-wrapper">
        <div class="card">
          <img src="https://plus.unsplash.com/premium_photo-1661284840324-dfe14d157fc8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1742&q=80" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>

        <div class="card">
          <img src="https://images.unsplash.com/flagged/photo-1570733117311-d990c3816c47?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>

        <div class="card">
          <img src="https://images.unsplash.com/flagged/photo-1553802922-5609062365b9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1742&q=80" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
    </div>

    <div class="carousel-item">
      <div class="cards-carousel-wrapper">
        <div class="card">
          <img src="https://images.unsplash.com/photo-1538329972958-465d6d2144ed?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>

        <div class="card">
          <img src="https://images.unsplash.com/photo-1493655161922-ef98929de9d8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>

        <div class="card">
          <img src="https://images.unsplash.com/flagged/photo-1570733117311-d990c3816c47?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
    </div>

    <div class="carousel-item">
      <div class="cards-carousel-wrapper">
        <div class="card">
          <img src="https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>

        <div class="card">
          <img src="https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>

        <div class="card">
          <img src="https://images.unsplash.com/photo-1469334031218-e382a71b716b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
    </div>

  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_homebaggrid.html.erb
<div class="container-home-grids">
  <div class="home-grids-div">
    <div class="home-grids-img-card">
  </div>

  <div class="home-grids-text-card">
    <h1 class="home-grids-text">monte sua sacola</h1>
    <p class="home-grids-parag">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Unde labore sequi eaque debitis inventore. Ab porro architecto sequi ratione neque voluptates dolore voluptatibus.</p>
    </div>
  </div>
</div>

app/views/shared/_productAddToinventory.erb
 <%= simple_form_for Product.new do |f| %>
    <%= f.input :name, label:"name" %>
    <%= f.input :category, label:"category" %>
    <%= f.input :price, label:"price" %>
    <%= f.input :image, label:"image" %>
    <%= f.color_field :color, label:"color" %>
    <%= f.input :size, label:"size", collection: 28..47, prompt: "Select the size", selected: 29, multiple: true  %>
    <%= f.input :size, label:"size", multiple: true %>
    <%= f.input :size, label:"size", as: :radio_buttons, collection: [['0', 'female'], ['1', 'male']], label_method: :second, value_method: :first, multiple:true %>
    <%= f.input :description, label:"description" %>

    <%= f.button :submit, 'Adicionar produto ao estoque',class:"btn btn-outline-success" %>
  <% end %>

app/views/shared/_productsAvailability.html.erb
<ul>
  <div class="card">
    <h1><%= "Colors available" %></h1>
    <p><%= @colors_available.join %></p>
    <p><%= "PS: As corres estão como teste. Estão como string, e não como array" %></p>
  </div>
</ul>

<ul>
  <div class="card">
    <h1><%= "Sizes available" %></h1>
    <p><%= @sizes_available.join %></p>
  </div>
</ul>

<ul>
  <div class="card">
    <h1><%= "Categories available" %></h1>
    <p><%= @categories_available.join %></p>
  </div>
</ul>

<ul>
  <div class="card">
    <h1><%= "Prices available" %></h1>
    <p><%= @prices_available.join %></p>
  </div>
</ul>

app/views/shared/_sectionTitle.html.erb
<section class="sections-container">
  <div class="sections-card">
    <div class="divider-container">
      <span class="nav-divider" style="height: 0.5px"></span>
    </div>

    <h1 class="sections-title js-animation">YOU</h1>
    <div class="divider-container">
      <span class="nav-divider" style="height: 2px"></span>
    </div>

    <h1 class="sections-subtitle js-animation">MODAS</h1>
    <div class="divider-container">
      <span class="nav-divider" style="height: 3px"></span>
    </div>

    <p class="sections-paragraph">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aspernatur dolores nobis harum deserunt quasi, modi iure, ipsum deleniti adipisci, nihil animi. Eius possimus eum acmus mollitia magnam rerum dolorum tenetur?</p>
  </div>
</section>

app/views/shared/_sectiontitle.html.erb
<section class="sections-container">
  <div class="sections-card">
    <div class="divider-container">
      <span class="nav-divider" style="height: 0.5px"></span>
    </div>

    <h1 class="sections-title js-animation">YOU</h1>
    <div class="divider-container">
      <span class="nav-divider" style="height: 2px"></span>
    </div>

    <h1 class="sections-subtitle js-animation">MODAS</h1>
    <div class="divider-container">
      <span class="nav-divider" style="height: 3px"></span>
    </div>

    <p class="sections-paragraph">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aspernatur dolores nobis harum deserunt quasi, modi iure, ipsum deleniti adipisci, nihil animi. Eius possimus eum acmus mollitia magnam rerum dolorum tenetur?</p>
  </div>
</section>

app/views/shared/_trendingGrid.html.erb
<section class="trending-grid-container">
  <div class="trending-img-div1">
    <img src="https://images.unsplash.com/photo-1572112686886-5c0b5bc8dacd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80" class="trending-grid-imgs" alt="">
  </div>

  <div class="trending-img-div2">
    <img src="https://images.unsplash.com/photo-1593409981958-562665d407cb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80" class="trending-grid-imgs" alt="">
  </div>

  <div class="trending-img-div3">
    <img src="https://images.unsplash.com/photo-1496440737103-cd596325d314?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80" class="trending-grid-imgs" alt="">
  </div>

  <div class="trending-img-div4">
    <img src="https://images.unsplash.com/photo-1495298599282-d8920eb5009b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80" class="trending-grid-imgs" alt="">
  </div>

  <div class="trending-img-div5">
    <img src="https://images.unsplash.com/photo-1456885284447-7dd4bb8720bf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80" class="trending-grid-imgs" alt="">
  </div>

  <div class="trending-img-div6">
    <img src="https://images.unsplash.com/photo-1512310604669-443f26c35f52?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=868&q=80" class="trending-grid-imgs" alt="">
  </div>

</section>

<div class="divider-container" style="margin-top: 50px">
  <span class="nav-divider" style="height: 2px; background-color: white"></span>
</div>